### ISSUE TITLE
Issue No. 1 :) are you still in development?

### ISSUE THREAD

**Issue by BobbySlope** [98oktay/homebridge-philips-tv6#1]
a HOOBS.org user just reported an issue

here's the log:

Initializing PhilipsTV accessory...
[Homebridge] [4/16/2020, 18:52:54] TypeError: Cannot read property 'forEach' of undefined
    at PhilipsTvAccessory.registerInputService (/home/hoobs/.hoobs/node_modules/homebridge-philips-tv6/index.js:101:16)
    at new PhilipsTvAccessory (/home/hoobs/.hoobs/node_modules/homebridge-philips-tv6/index.js:28:14)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:269:35)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] [4/16/2020, 18:52:54] Got SIGTERM, shutting down service...

here's the config part:

 "accessories": [
        {
            "accessory": "PhilipsTV",
            "name": "TV",
            "ip_address": "192.168.5.66",
            "poll_status_interval": "30",
            "model_year": 2019,
            "has_ambilight": true,
            "wol_url": "wol://70:af:24:ba:ac:7a",
            "username": "XGOpv4XSRLfQnIKg",
            "password": " 2c384bbeeba2a42c3333ade6fb26a7cd8bd81dab81f426577b0424b72f8c0600"
        }
    ],

Tv Model: 58PUS7304

can u help with that?

**Comment by 98oktay** [comment]
Hello friend,
Yes, I keep improving. I think I made the "inputs" value required. Thank you for reporting.
You can temporarily add the empty array "**inputs: []**" to the configuration.
I am solving this problem immediately.

**Comment by BobbySlope** [comment]
thanks for the quick response,
same error again.

[Homebridge] [4/16/2020, 19:28:02] TypeError: Cannot read property 'forEach' of undefined
    at PhilipsTvAccessory.registerInputService (/home/hoobs/.hoobs/node_modules/homebridge-philips-tv6/index.js:101:16)
    at new PhilipsTvAccessory (/home/hoobs/.hoobs/node_modules/homebridge-philips-tv6/index.js:28:14)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:269:35)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] [4/16/2020, 19:28:02] Got SIGTERM, shutting down service...

**Comment by 98oktay** [comment]
I released a new package version. I believe this will solve the problem.

**Comment by woots82** [comment]
Hello there I have installed the update and can now turn the tv off and on :)
Is there a way to add HDMI inputs?

**Comment by 98oktay** [comment]
> Hello there I have installed the update and can now turn the tv off and on :)
> Is there a way to add HDMI inputs?

It does not support this feature yet. I will do it when I find a method.

**Comment by juju35** [comment]
> > Hello there I have installed the update and can now turn the tv off and on :)
> > Is there a way to add HDMI inputs?
> 
> It does not support this feature yet. I will do it when I find a method.

It is done in this Homebridge Plugin [https://github.com/TheAbstractDev/homebridge-philips-saphi-tv/blob/master/index.js](url)

**Comment by woots82** [comment]
Unfortunately I have the Android TV os not saphi

**Comment by 98oktay** [comment]
> > > Hello there I have installed the update and can now turn the tv off and on :)
> > > Is there a way to add HDMI inputs?
> > 
> > 
> > It does not support this feature yet. I will do it when I find a method.
> 
> It is done in this Homebridge Plugin [https://github.com/TheAbstractDev/homebridge-philips-saphi-tv/blob/master/index.js](url)

I've seen this before. Pressing the "source", "down", "confirm" keys on the controller respectively. It didn't come to me as a reliable method.

**Comment by woots82** [comment]
Please see log, think the plug in is timing out something..

[Homebridge] at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:848:19)
[Homebridge] at listOnTimeout (internal/timers.js:531:17)
[Homebridge] at processTimers (internal/timers.js:475:7)
[Homebridge] (node:3643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 194)

**Comment by woots82** [comment]
Hi

Plugin not working, on / off unresponsive

**Comment by Feelisreal** [comment]
@98oktay Hey I've been fiddeling with your plugin, trying to adjust it to my needs. I have a non Android Philips TV with JointSpace. I got some things to work (on/off, volume). Now I am trying a) to use the volume/lightbulb to adjust my Sonos Soundbar instead of TV and b) to be able to switch the input source and Channel. I get the Channel to work halfway via the (old) input/key. With sources/current I get {"id":"tv"} which I can work with within your code. I can even post a {"id":"hdmi1"} for example to change to hdmi1 and it works (testing mostly via Postman though). My biggest issue now is that the JointSpace seems broken when GETing sources/current for all hdmi sources which always returns {"id":"unknown"} that way I am never able to get the current source right and set it as selected. I would not mind if it was only a UI issue (not showing the selected input source) but appearently it messes up the whole procedure and I can neither set nor get any source properly. Help would be much apreceated (it would enable me to get rid of my two other remote controls). But I would totaly understand if it is to much to ask. I am not a coder just a hobby enthusiast. Thanks for your nice plugin anyways!
